# Generated by Django 4.0 on 2024-08-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='last_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
