# Generated by Django 4.0 on 2024-08-18 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_mailingsettings_last_sent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='date_next',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='следующая дата рассылки'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала рассылки'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активация рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Created'), ('L', 'Launched'), ('I', 'Inactive')], default='I', max_length=2, null=True),
        ),
    ]
