# Generated by Django 4.0 on 2024-08-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_mailingsettings_date_next_mailingsettings_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
